FROM golang:1.24.1-alpine

WORKDIR /workspace

COPY go.mod go.sum ./

RUN go mod download

ADD . .

RUN go build -o .build/deployer -ldflags "-w -s" .

FROM alpine:3.21

WORKDIR /app

COPY --from=0 --link /workspace/.build/* ./
ENTRYPOINT ["/app/deployer"]
