FROM golang:1.24.1-alpine
RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

ENTRYPOINT ["CompileDaemon", "--build=go build -o /opt/app/app", "--command=/opt/app/app", "--build-dir=/app"]
